Repository netlify/js-client, pull requests merged in 2020-04, with the labels that each got.

#94 Fix linting
  .eslintrc.json
  package.json
  src/deploy/hash-fns.js
  src/deploy/hasher-segments.js
  src/deploy/index.js
  src/deploy/upload-files.js
  src/deploy/util.js
  src/index.js
  src/index.test.js
  src/methods/index.js
  src/methods/url.js
Labels: type: chore

#96 Commit lock file
  .gitignore
  package-lock.json
Labels: type: chore

#95 Upgrade dependencies
  package-lock.json
  package.json
Labels: type: chore

#98 Fix `npm audit` warnings
  package-lock.json
Labels: type: security

#97 Reorganize development setup
  .github/workflows/workflow.yml
  ava.config.js
  package.json
  scripts/coverage.sh
Labels: type: chore

#100 Add http.Agent option
  README.md
  src/index.js
  src/index.test.js
  src/methods/index.js
Labels: type: feature
