Repository netlify/js-client, pull requests merged in 2020-10, with the labels that each got.

#171 Retry on `ETIMEDOUT` timeout
  src/index.test.js
  src/methods/index.js
  src/methods/retry.js
Labels: type: bug

#172 Small improvement of the test logic
  package-lock.json
  package.json
  src/index.test.js
Labels: type: chore

#181 align js-client upload limits with api ones
  README.md
  src/deploy/index.js
Labels: reliability, type: chore

#184 ci: don't run format and build on node 8
  .github/workflows/workflow.yml
Labels: type: chore

#187 chore: fix lockfile
  package-lock.json
Labels: type: chore

#186 chore(deps): update eslint and prettier
  README.md
  ava.config.js
  package-lock.json
  package.json
  renovate.json5
  src/addons.js
  src/deploy/hash-files.js
  src/deploy/hash-files.test.js
  src/deploy/hash-fns.js
  src/deploy/hash-fns.test.js
  src/deploy/hasher-segments.js
  src/deploy/index.js
  src/deploy/upload-files.js
  src/deploy/util.js
  src/deploy/util.test.js
  src/index.js
  src/index.test.js
  src/methods/body.js
  src/methods/index.js
  src/methods/response.js
  src/methods/retry.js
  src/methods/url.js
  src/operations.js
  src/operations.test.js
  src/utils/omit.js
  webpack.config.js
Labels: type: chore
