Repository netlify/js-client, pull requests merged in 2021-05, with the labels that each got.

#411 fix: array query parameters
  src/index.test.js
  src/methods/url.js
Labels: type: bug

#432 chore: fix test coverage upload
  .github/workflows/workflow.yml
Labels: type: chore

#437 feat!: remove deploy method
  README.md
  package-lock.json
  package.json
  src/deploy/constants.js
  src/deploy/hash_files.js
  src/deploy/hash_files.test.js
  src/deploy/hash_fns.js
  src/deploy/hash_fns.test.js
  src/deploy/hasher_segments.js
  src/deploy/index.browser.js
  src/deploy/index.js
  src/deploy/upload_files.js
  src/deploy/util.js
  src/deploy/util.test.js
  src/index.js
Labels: type: feature
